# Generated by Django 3.0 on 2020-07-30 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentid', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
